"""
Correlation Engine for SentinelAI.
Groups related open alerts into incidents based on shared attributes
(source IP, destination IP, alert type, severity, time window).
"""
from collections import defaultdict
from datetime import datetime, timezone, timedelta
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field, asdict


@dataclass
class CorrelatedIncident:
    """An incident generated by correlating multiple alerts."""
    title: str
    severity: str
    description: str = ""
    alert_ids: List[str] = field(default_factory=list)
    timeline: List[Dict[str, Any]] = field(default_factory=list)
    affected_ips: List[str] = field(default_factory=list)
    mitre_techniques: List[str] = field(default_factory=list)
    mitre_tactics: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)
    confidence: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class CorrelationEngine:
    """Correlates open alerts into incidents based on shared attributes and time windows."""

    def __init__(self):
        self.TIME_WINDOW_MINUTES = 60
        self.MIN_ALERTS_FOR_INCIDENT = 1

    def correlate(self, alerts: List[Dict]) -> List[CorrelatedIncident]:
        """Group related alerts into incidents."""
        if not alerts:
            return []

        # Build groups keyed by correlation keys
        groups: Dict[str, List[Dict]] = defaultdict(list)

        for alert in alerts:
            alert_id = alert.get("id", "")
            source_ip = alert.get("source_ip", "")
            dest_ip = alert.get("destination_ip", "")
            alert_type = alert.get("alert_type", "")
            severity = alert.get("severity", "INFO")
            created_at = alert.get("created_at", "")

            # Correlation keys: group by source_ip + alert_type, dest_ip + alert_type, and severity
            keys = set()
            if source_ip:
                keys.add(f"src:{source_ip}:{alert_type}")
                keys.add(f"src:{source_ip}:*")
            if dest_ip:
                keys.add(f"dst:{dest_ip}:{alert_type}")
                keys.add(f"dst:{dest_ip}:*")
            keys.add(f"type:{alert_type}")
            keys.add(f"sev:{severity}")

            for key in keys:
                groups[key].append(alert)

        # Merge overlapping groups by finding alerts that appear in multiple groups
        merged: List[List[Dict]] = []
        seen_alert_ids: set = set()

        # Sort groups by size (largest first) for greedy merging
        sorted_groups = sorted(groups.values(), key=len, reverse=True)

        for group_alerts in sorted_groups:
            group_ids = {a.get("id") for a in group_alerts}
            # Skip if all alerts already assigned
            if group_ids & seen_alert_ids:
                continue
            merged.append(group_alerts)
            seen_alert_ids |= group_ids

        # Build incidents from merged groups
        incidents: List[CorrelatedIncident] = []
        for group in merged:
            if len(group) < self.MIN_ALERTS_FOR_INCIDENT:
                continue
            incident = self._build_incident(group)
            if incident:
                incidents.append(incident)

        return incidents

    def _build_incident(self, alerts: List[Dict]) -> Optional[CorrelatedIncident]:
        """Create a CorrelatedIncident from a group of related alerts."""
        if not alerts:
            return None

        # Aggregate attributes
        alert_ids = []
        affected_ips = set()
        all_techniques = set()
        all_tactics = set()
        timeline = []
        severities = []
        alert_types = []

        for alert in alerts:
            alert_id = alert.get("id", "")
            if alert_id:
                alert_ids.append(alert_id)

            sip = alert.get("source_ip", "")
            dip = alert.get("destination_ip", "")
            if sip:
                affected_ips.add(sip)
            if dip:
                affected_ips.add(dip)

            technique = alert.get("mitre_technique", "")
            if technique:
                all_techniques.add(technique)
            tactic = alert.get("mitre_tactic", "")
            if tactic:
                all_tactics.add(tactic)

            created_at = alert.get("created_at", "")
            timeline.append({
                "alert_id": alert_id,
                "timestamp": created_at,
                "title": alert.get("title", ""),
                "severity": alert.get("severity", ""),
                "type": alert.get("alert_type", ""),
            })

            sev = alert.get("severity", "INFO")
            severities.append(sev)
            atype = alert.get("alert_type", "unknown")
            alert_types.append(atype)

        if not alert_ids:
            return None

        # Determine incident severity (use highest)
        severity_order = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1, "INFO": 0}
        max_severity = max(severities, key=lambda s: severity_order.get(s, 0))

        # Build title
        type_counts = defaultdict(int)
        for t in alert_types:
            type_counts[t] += 1
        top_types = sorted(type_counts.items(), key=lambda x: -x[1])
        type_str = ", ".join(f"{t} ({c})" for t, c in top_types[:3])
        ip_count = len(affected_ips)
        title = f"Incident: {type_str} — {len(alert_ids)} alerts, {ip_count} IP(s)"

        # Build description
        description = (
            f"Correlated {len(alert_ids)} related alert(s) into a single incident. "
            f"Alert types: {type_str}. "
            f"Affected IPs: {', '.join(sorted(affected_ips)) if affected_ips else 'N/A'}."
        )

        # Map attack types to recommendations
        recommendations = self._build_recommendations(alert_types, max_severity)

        # Compute confidence based on number of correlated alerts
        confidence = min(0.5 + len(alert_ids) * 0.05, 0.99)

        timeline.sort(key=lambda t: t.get("timestamp", ""))

        return CorrelatedIncident(
            title=title,
            severity=max_severity,
            description=description,
            alert_ids=alert_ids,
            timeline=timeline,
            affected_ips=sorted(affected_ips),
            mitre_techniques=sorted(all_techniques),
            mitre_tactics=sorted(all_tactics),
            recommendations=recommendations,
            confidence=round(confidence, 3),
        )

    def _build_recommendations(self, alert_types: List[str], severity: str) -> List[str]:
        """Build recommendations based on alert types and severity."""
        recs = []
        unique_types = set(alert_types)

        if severity in ("CRITICAL", "HIGH"):
            recs.append("Escalate to senior analyst immediately")
            recs.append("Enable enhanced monitoring on affected systems")

        if "brute_force" in unique_types or "credential_stuffing" in unique_types:
            recs.append("Block source IPs after threshold exceeded")
            recs.append("Enable account lockout policy")
            recs.append("Enforce MFA on all accounts")

        if "port_scan" in unique_types:
            recs.append("Enable port scan detection on IDS/IPS")
            recs.append("Audit firewall rules and close unnecessary ports")

        if "dos" in unique_types or "ddos" in unique_types:
            recs.append("Activate DDoS mitigation service")
            recs.append("Enable rate limiting on public endpoints")
            recs.append("Scale bandwidth if under active attack")

        if "web_attack" in unique_types:
            recs.append("Deploy WAF rules for detected attack pattern")
            recs.append("Review and patch vulnerable web endpoints")

        if "data_exfiltration" in unique_types:
            recs.append("Block unauthorized outbound connections")
            recs.append("Engage incident response team")

        if "beaconing" in unique_types or "bot" in unique_types:
            recs.append("Isolate compromised endpoint")
            recs.append("Block C2 server IPs at perimeter firewall")

        # Always add
        recs.append("Preserve forensic evidence (logs, memory dumps)")
        recs.append("Document all findings in incident timeline")

        return recs


correlation_engine = CorrelationEngine()
