"""
Attack-Stage-Aware Correlation Engine for SentinelAI.
Groups related alerts into incidents based on kill chain progression,
not just alert counts.

Real SOC correlation considers:
- Time proximity (events within a window)
- Host/IP association (same source or target)
- Attack stage progression (recon → exploit → lateral movement → exfil)
- Alert severity escalation
"""

from collections import defaultdict
from datetime import datetime, timezone, timedelta
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass, field, asdict


# ─── Kill Chain Stage Mapping ─────────────────────────────────────────────────

# Maps alert types to kill chain stages (lower = earlier)
KILL_CHAIN_STAGES = {
    # Stage 1: Reconnaissance
    "port_scan": 1,
    "network_scan": 1,
    "dns_enumeration": 1,
    "vulnerability_scan": 1,
    # Stage 2: Initial Access
    "failed_logon": 2,
    "brute_force": 2,
    "ssh_failed": 2,
    "web_attack": 2,
    "phishing": 2,
    "credential_stuffing": 2,
    "sql_injection": 2,
    "xss_attack": 2,
    "path_traversal": 2,
    # Stage 3: Execution
    "process_created": 3,
    "powershell_execution": 3,
    "script_execution": 3,
    "service_install": 3,
    # Stage 4: Persistence
    "user_created": 4,
    "user_deleted": 4,
    "group_member_added": 4,
    "local_group_member_added": 4,
    "scheduled_task": 4,
    "registry_modification": 4,
    # Stage 5: Privilege Escalation
    "sudo_command": 5,
    "explicit_logon": 5,
    "token_manipulation": 5,
    # Stage 6: Defense Evasion
    "audit_cleared": 6,
    "log_cleared": 6,
    "timestomping": 6,
    # Stage 7: Credential Access
    "credential_dumping": 7,
    "kerberoasting": 7,
    "password_spraying": 7,
    # Stage 8: Discovery
    "lateral_movement": 8,
    "network_discovery": 8,
    # Stage 9: Lateral Movement
    "remote_access": 9,
    "smb_lateral": 9,
    # Stage 10: Collection
    "data_staging": 10,
    # Stage 11: Exfiltration
    "data_exfiltration": 11,
    "beaconing": 11,
    "c2_communication": 11,
    "bot": 11,
    # Stage 12: Impact
    "dos": 12,
    "ddos": 12,
    "ransomware": 12,
    "data_destruction": 12,
}

STAGE_NAMES = {
    1: "Reconnaissance",
    2: "Initial Access",
    3: "Execution",
    4: "Persistence",
    5: "Privilege Escalation",
    6: "Defense Evasion",
    7: "Credential Access",
    8: "Discovery",
    9: "Lateral Movement",
    10: "Collection",
    11: "Exfiltration",
    12: "Impact",
}

# Attack chain patterns (ordered sequences that indicate compromise)
ATTACK_CHAINS = {
    "credential_compromise": {
        "stages": [2, 5, 3, 9],  # Failed logon → sudo/explicit → process → lateral
        "name": "Credential Compromise",
        "severity_boost": 1,  # Increase severity by 1 level
        "description": "Attacker likely obtained credentials and is moving laterally",
    },
    "data_breach": {
        "stages": [2, 3, 8, 10, 11],  # Access → execution → discovery → staging → exfil
        "name": "Data Breach",
        "severity_boost": 2,
        "description": "Potential data exfiltration detected — attacker has reached collection/exfil stage",
    },
    "insider_threat": {
        "stages": [5, 6, 8, 11],  # Priv esc → evasion → discovery → exfil
        "name": "Insider Threat",
        "severity_boost": 1,
        "description": "Pattern suggests insider with legitimate access conducting unauthorized activity",
    },
    "apt_activity": {
        "stages": [1, 2, 3, 4, 7, 8, 9],
        "name": "APT Activity",
        "severity_boost": 2,
        "description": "Advanced persistent threat — multi-stage attack progression detected",
    },
    "ransomware_prep": {
        "stages": [3, 4, 7, 8, 12],
        "name": "Ransomware Preparation",
        "severity_boost": 2,
        "description": "Attack chain consistent with ransomware deployment preparation",
    },
    "web_exploitation": {
        "stages": [1, 2, 3, 4],
        "name": "Web Application Exploitation",
        "severity_boost": 1,
        "description": "Web application attack leading to code execution and persistence",
    },
}


@dataclass
class CorrelatedIncident:
    """An incident generated by correlating related alerts."""
    title: str
    severity: str
    description: str = ""
    alert_ids: List[str] = field(default_factory=list)
    timeline: List[Dict[str, Any]] = field(default_factory=list)
    affected_ips: List[str] = field(default_factory=list)
    affected_hosts: List[str] = field(default_factory=list)
    mitre_techniques: List[str] = field(default_factory=list)
    mitre_tactics: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)
    confidence: float = 0.0
    kill_chain_stages: List[str] = field(default_factory=list)
    matched_chain: str = ""
    severity_score: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class CorrelationEngine:
    """Attack-stage-aware correlation engine."""

    def __init__(self):
        self.TIME_WINDOW_MINUTES = 60
        self.MIN_ALERTS_FOR_INCIDENT = 2

    def correlate(self, alerts: List[Dict]) -> List[CorrelatedIncident]:
        """Group related alerts into incidents using multi-dimensional correlation."""
        if not alerts:
            return []

        # Step 1: Group alerts by correlation dimensions
        groups = self._build_correlation_groups(alerts)

        # Step 2: Merge overlapping groups
        merged_groups = self._merge_groups(groups)

        # Step 3: Build incidents from merged groups
        incidents = []
        for group in merged_groups:
            if len(group) < self.MIN_ALERTS_FOR_INCIDENT:
                continue
            incident = self._build_incident(group)
            if incident:
                incidents.append(incident)

        return incidents

    def _build_correlation_groups(self, alerts: List[Dict]) -> Dict[str, List[Dict]]:
        """Build correlation groups using multiple dimensions."""
        groups: Dict[str, List[Dict]] = defaultdict(list)

        for alert in alerts:
            alert_id = alert.get("id", "")
            source_ip = alert.get("source_ip", "")
            dest_ip = alert.get("destination_ip", "")
            alert_type = alert.get("alert_type", "")
            severity = alert.get("severity", "INFO")
            created_at = alert.get("created_at", "")
            device_id = alert.get("device_id", "")

            # Get kill chain stage for this alert type
            stage = KILL_CHAIN_STAGES.get(alert_type, 0)

            # Dimension 1: IP-based grouping (same attacker)
            if source_ip:
                groups[f"ip:{source_ip}"].append(alert)

            # Dimension 2: Host-based grouping (same target)
            if device_id:
                groups[f"host:{device_id}"].append(alert)

            # Dimension 3: Kill chain stage grouping
            if stage:
                groups[f"stage:{stage}"].append(alert)

            # Dimension 4: Attack chain pattern grouping
            for chain_name, chain_info in ATTACK_CHAINS.items():
                if stage in chain_info["stages"]:
                    groups[f"chain:{chain_name}"].append(alert)

            # Dimension 5: Severity escalation grouping
            if severity in ("CRITICAL", "HIGH"):
                groups[f"severity:{severity}"].append(alert)

        return groups

    def _merge_groups(self, groups: Dict[str, List[Dict]]) -> List[List[Dict]]:
        """Merge overlapping groups using alert ID intersection."""
        all_groups = list(groups.values())
        merged: List[List[Dict]] = []
        seen_ids: set = set()

        # Sort by group size (largest first) for greedy merging
        all_groups.sort(key=len, reverse=True)

        for group in all_groups:
            group_ids = {a.get("id") for a in group}
            # Skip if all alerts already assigned to a merged group
            if group_ids & seen_ids:
                continue
            merged.append(group)
            seen_ids |= group_ids

        return merged

    def _build_incident(self, alerts: List[Dict]) -> Optional[CorrelatedIncident]:
        """Build a CorrelatedIncident from a group of related alerts."""
        if not alerts:
            return None

        # Sort by timestamp
        alerts.sort(key=lambda a: a.get("created_at", ""))

        # Aggregate attributes
        alert_ids = []
        affected_ips = set()
        affected_hosts = set()
        all_techniques = set()
        all_tactics = set()
        timeline = []
        severities = []
        alert_types = []
        stages = set()

        for alert in alerts:
            alert_id = alert.get("id", "")
            if alert_id:
                alert_ids.append(alert_id)

            sip = alert.get("source_ip", "")
            dip = alert.get("destination_ip", "")
            if sip:
                affected_ips.add(sip)
            if dip:
                affected_ips.add(dip)

            device_id = alert.get("device_id", "")
            if device_id:
                affected_hosts.add(device_id)

            technique = alert.get("mitre_technique", "")
            if technique:
                all_techniques.add(technique)
            tactic = alert.get("mitre_tactic", "")
            if tactic:
                all_tactics.add(tactic)

            atype = alert.get("alert_type", "unknown")
            stage = KILL_CHAIN_STAGES.get(atype, 0)
            if stage:
                stages.add(stage)

            created_at = alert.get("created_at", "")
            timeline.append({
                "alert_id": alert_id,
                "timestamp": created_at,
                "title": alert.get("title", ""),
                "severity": alert.get("severity", ""),
                "type": atype,
                "source_ip": sip,
                "stage": STAGE_NAMES.get(stage, "Unknown") if stage else "Unknown",
            })

            severities.append(alert.get("severity", "INFO"))
            alert_types.append(atype)

        if not alert_ids:
            return None

        # Determine severity (use highest + chain boost)
        severity_order = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1, "INFO": 0}
        max_sev = max(severities, key=lambda s: severity_order.get(s, 0))
        max_sev_num = severity_order.get(max_sev, 0)

        # Check for matching attack chain
        matched_chain = ""
        chain_boost = 0
        for chain_name, chain_info in ATTACK_CHAINS.items():
            chain_stages = set(chain_info["stages"])
            if stages & chain_stages:  # If any of our stages match the chain
                overlap = len(stages & chain_stages)
                if overlap >= 2:  # At least 2 matching stages
                    if chain_info["severity_boost"] > chain_boost:
                        matched_chain = chain_name
                        chain_boost = chain_info["severity_boost"]

        # Apply severity boost from chain match
        boosted_sev_num = min(max_sev_num + chain_boost, 4)
        severity_names = {0: "INFO", 1: "LOW", 2: "MEDIUM", 3: "HIGH", 4: "CRITICAL"}
        final_severity = severity_names.get(boosted_sev_num, "MEDIUM")

        # Build kill chain stage list
        sorted_stages = sorted(stages)
        kill_chain_stages = [STAGE_NAMES.get(s, f"Stage {s}") for s in sorted_stages]

        # Build title
        if matched_chain:
            chain_info = ATTACK_CHAINS[matched_chain]
            title = f"{chain_info['name']} — {len(alert_ids)} alerts, {len(affected_ips)} IP(s)"
        else:
            type_counts = defaultdict(int)
            for t in alert_types:
                type_counts[t] += 1
            top_types = sorted(type_counts.items(), key=lambda x: -x[1])
            type_str = ", ".join(f"{t.replace('_', ' ').title()} ({c})" for t, c in top_types[:3])
            title = f"{final_severity}: {type_str} — {len(alert_ids)} alerts"

        # Build description
        if matched_chain:
            chain_info = ATTACK_CHAINS[matched_chain]
            description = (
                f"{chain_info['description']}. "
                f"Kill chain progression: {' → '.join(kill_chain_stages)}. "
                f"Affected IPs: {', '.join(sorted(affected_ips)) if affected_ips else 'N/A'}."
            )
        else:
            description = (
                f"Correlated {len(alert_ids)} related alerts. "
                f"Types: {', '.join(sorted(set(alert_types)))}. "
                f"Kill chain stages: {', '.join(kill_chain_stages) if kill_chain_stages else 'N/A'}."
            )

        # Build recommendations
        recommendations = self._build_recommendations(alert_types, final_severity, matched_chain, stages)

        # Compute confidence based on chain progression and alert count
        base_confidence = min(0.4 + len(alert_ids) * 0.05, 0.7)
        chain_bonus = 0.15 if matched_chain else 0
        stage_bonus = min(len(stages) * 0.03, 0.15)
        confidence = min(base_confidence + chain_bonus + stage_bonus, 0.99)

        # Compute severity score (0-10)
        severity_score = (boosted_sev_num / 4) * 10

        return CorrelatedIncident(
            title=title,
            severity=final_severity,
            description=description,
            alert_ids=alert_ids,
            timeline=timeline,
            affected_ips=sorted(affected_ips),
            affected_hosts=sorted(affected_hosts),
            mitre_techniques=sorted(all_techniques),
            mitre_tactics=sorted(all_tactics),
            recommendations=recommendations,
            confidence=round(confidence, 3),
            kill_chain_stages=kill_chain_stages,
            matched_chain=matched_chain,
            severity_score=round(severity_score, 1),
        )

    def _build_recommendations(self, alert_types: List[str], severity: str,
                                matched_chain: str, stages: set) -> List[str]:
        """Build recommendations based on alert types, severity, and kill chain stage."""
        recs = []
        unique_types = set(alert_types)

        # Chain-specific recommendations
        if matched_chain == "credential_compromise":
            recs.append("Immediately reset credentials for affected accounts")
            recs.append("Enable MFA on all privileged accounts")
            recs.append("Review authentication logs for anomalous patterns")
            recs.append("Isolate affected endpoints from network")

        elif matched_chain == "data_breach":
            recs.append("Engage incident response team immediately")
            recs.append("Block all outbound connections from affected hosts")
            recs.append("Preserve forensic evidence (memory dumps, disk images)")
            recs.append("Notify data protection officer if PII involved")

        elif matched_chain == "insider_threat":
            recs.append("Disable affected user accounts pending investigation")
            recs.append("Review access logs for all activity by suspicious users")
            recs.append("Engage HR and legal teams")
            recs.append("Monitor all data transfers from affected accounts")

        elif matched_chain == "apt_activity":
            recs.append("Activate full incident response protocol")
            recs.append("Deploy threat hunting team to affected network segment")
            recs.append("Check for indicators of compromise across entire environment")
            recs.append("Contact cybersecurity insurance provider")

        elif matched_chain == "ransomware_prep":
            recs.append("ISOLATE AFFECTED SYSTEMS IMMEDIATELY")
            recs.append("Disable file sharing services (SMB, RDP)")
            recs.append("Verify backup integrity and offline copies")
            recs.append("Deploy ransomware-specific detection rules")

        elif matched_chain == "web_exploitation":
            recs.append("Deploy WAF rules for detected attack pattern")
            recs.append("Review and patch vulnerable web endpoints")
            recs.append("Enable enhanced logging on web servers")

        # Stage-based recommendations
        if 7 in stages:  # Credential Access
            recs.append("Force password reset for all accounts on affected systems")
        if 9 in stages:  # Lateral Movement
            recs.append("Segment network to limit lateral movement")
        if 11 in stages:  # Exfiltration
            recs.append("Block unauthorized outbound connections at firewall")
            recs.append("Monitor DNS traffic for tunneling indicators")
        if 12 in stages:  # Impact
            recs.append("Activate business continuity plan")

        # Severity-based
        if severity in ("CRITICAL", "HIGH"):
            recs.append("Escalate to senior analyst immediately")
            recs.append("Enable enhanced monitoring on affected systems")

        # Type-specific
        if "brute_force" in unique_types or "credential_stuffing" in unique_types:
            recs.append("Block source IPs after threshold exceeded")
            recs.append("Enable account lockout policy")
        if "port_scan" in unique_types:
            recs.append("Audit firewall rules and close unnecessary ports")
        if "dos" in unique_types or "ddos" in unique_types:
            recs.append("Activate DDoS mitigation service")
            recs.append("Enable rate limiting on public endpoints")
        if "data_exfiltration" in unique_types:
            recs.append("Engage incident response team")
        if "beaconing" in unique_types or "bot" in unique_types:
            recs.append("Isolate compromised endpoint")
            recs.append("Block C2 server IPs at perimeter firewall")

        # Always add
        recs.append("Preserve forensic evidence (logs, memory dumps)")
        recs.append("Document all findings in incident timeline")

        return recs


correlation_engine = CorrelationEngine()
